### ISSUE TITLE
Amazon Glacier Support?

### ISSUE THREAD

**Issue by buehler** [tutumcloud/dockup#11]
Hey tutum!

I got a question about dockup

Is it possible to upload the files into a amazon glacier vault instead of a S3 bucket?

Cheers
Chris

**Comment by cggaurav** [comment]
+1 because Glacier's Data in is $0 and storage is 10x cheaper than S3.

**Comment by rarous** [comment]
You may move cold backups to Glacier, but do not skip S3.

**Comment by buehler** [comment]
maybe we close this issue? since tutum is beeing deprecated with dockercloud?

**Comment by cggaurav** [comment]
Yeah, we need migrate these issues on dockercloud/dockup instead.
